## color theme
[[plugins]]
repo = 'nanotech/jellybeans.vim'


## File
### Tree finder
[[plugins]]
hook_add = """
    nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
"""
repo = 'lambdalisue/fern.vim'

# fren.vimに乗り換えた
# [[plugins]]
# repo = 'scrooloose/nerdtree'


### Fuzzy finder
[[plugins]]
hook_post_update = './install --all'
merged = 0
repo = 'junegunn/fzf'

[[plugins]]
hook_add = """
    command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
    \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
    \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
    \ <bang>0)
"""
depends = 'fzf'
repo = 'junegunn/fzf.vim'

[[plugins]]
hook_add = """
    let g:airline_powerline_fonts = 1
    let g:webdevicons_enable_nerdtree = 1
    let g:webdevicons_conceal_nerdtree_brackets = 1
"""
repo = 'ryanoasis/vim-devicons'


## window decoration
[[plugins]]
repo = 'vim-airline/vim-airline-themes'


# https://github.com/vim-airline/vim-airline/wiki/Screenshots
[[plugins]]
hook_add = """
    let g:airline_theme='angr'
    let g:airline#extensions#tabline#enabled=1
    let g:airline#extensions#tabline#formatter='unique_tail'
    let g:airline#extensions#tabline#buffer_idx_mode=1
    let g:airline#extensions#tabline#buffer_idx_format = {
        \ '0': '0 ',
        \ '1': '1 ',
        \ '2': '2 ',
        \ '3': '3 ',
        \ '4': '4 ',
        \ '5': '5 ',
        \ '6': '6 ',
        \ '7': '7 ',
        \ '8': '8 ',
        \ '9': '9 '
        \}
    let g:airline#extensions#branch#enabled=1
    let g:airline#extensions#hunks#enabled=1
    let g:airline#extensions#tabline#enabled=1
    let g:airline#extensions#wordcount#enabled=1
    let g:airline#extensions#branch#vcs_checks = []
    let g:airline#extensions#default#layout=[['a', 'b', 'c'], ['wordcount', 'error', 'warning', 'x', 'y', 'z']]
    let g:airline_section_c = '%t'
"""
repo = 'vim-airline/vim-airline'
# [[plugins]]
# repo = 'tpope/vim-fugitive' # show branch-name on vim-airline window


[[plugins]]
hook_add = """
    let g:indent_guides_enable_on_vim_startup=1 "デフォルトでインデント出す
    let g:indent_guides_start_level=2 "ガイドをスタートするインデント
    let g:indent_guides_guide_size=1 " ガイドの幅
    let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=gray "奇数インデントのカラー
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=darkgray "偶数インデントのカラー
"""
repo = 'nathanaelkane/vim-indent-guides'


## git
[[plugins]]
repo = 'airblade/vim-gitgutter' # show diff


## shortuts
[[plugins]]
hook_add = """
    nnoremap <C-/> <Plug>RepeatTComment<CR>
"""
repo = 'tomtom/tcomment_vim' # comment out

[[plugins]]
repo = 'easymotion/vim-easymotion' # make it easy to move few words


## lsp
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
" TypeScript, JavaScript
if executable('typescript-language-server')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'package.json'))},
"       \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
        \ 'whitelist': ['typescript', 'typescript.tsx', 'javascript', 'javascript.jsx'],
        \ })
endif

" 他言語サーバの読み込みはここに挿入
'''
[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'shun/ddc-vim-lsp'
[[plugins]]
repo = 'Shougo/ddc-ui-native'
#Install Your Sources
[[plugins]]
repo = 'Shougo/ddc-source-around'
# Install your filters
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'matsui54/ddc-buffer'
[[plugins]]
reop = 'shun/ddc-source-vim-lsp'
[[plugins]]
repo = 'tani/ddc-fuzzy'


[[plugins]]
repo = 'hrsh7th/nvim-cmp'
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/vim-vsnip'


### js
[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
hook_add = '''
    source ~/.config/nvim/plugins/vim-vue.rc.vim
'''
repo = 'posva/vim-vue'


[[plugins]]
on_ft = ['pug', 'vue']
repo = 'digitaltoad/vim-pug'

[[plugins]]
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
repo = 'prettier/vim-prettier'


[[plugins]]
repo = 'alvan/vim-closetag'

## copilot
[[plugins]]
repo = 'github/copilot.vim'

