## color theme
[[plugins]]
hook_add = '''
    colorscheme slate
'''
repo = 'nanotech/jellybeans.vim'

## git
[[plugins]]
hook_add = '''
    set updatetime=250 " gitgutterの更新時間を短くする
    let g:gitgutter_highlight_lines=0 " 変更行をハイライト
    highlight GitGutterAdd ctermfg=NONE
    highlight GitGutterChange ctermfg=NONE
    highlight GitGutterDelete ctermfg=NONE
    let g:gitgutter_sign_added = '+'
    let g:gitgutter_sign_modified = '|'
    let g:gitgutter_sign_removed = '-'
    let g:gitgutter_sign_removed_first_line = '^'
    let g:gitgutter_sign_modified_removed = 'w'
    let g:gitgutter_override_sign_column_highlight=1 " サインカラムのハイライトを上書き
'''
repo = 'airblade/vim-gitgutter' # show diff

[[plugins]]
repo = 'tpope/vim-fugitive' #Gdiff

## File
### Tree finder
[[plugins]]
hook_add = """
    nnoremap fn :Fern . -reveal=% -drawer -toggle -width=40<CR>
"""
repo = 'lambdalisue/fern.vim'

# fren.vimに乗り換えた
# [[plugins]]
# repo = 'scrooloose/nerdtree'


### Fuzzy finder
[[plugins]]
hook_post_update = './install --all'
merged = 0
repo = 'junegunn/fzf'

[[plugins]]
depends = 'junegunn/fzf'
repo = 'junegunn/fzf.vim'

[[plugins]]
hook_add = """
let g:airline_powerline_fonts = 1
let g:webdevicons_enable_nerdtree = 1
let g:webdevicons_conceal_nerdtree_brackets = 1
"""
repo = 'ryanoasis/vim-devicons'

# [[plugins]]
# repo = 'jremmen/vim-ripgrep'

## window decoration
[[plugins]]
repo = 'vim-airline/vim-airline-themes'


# https://github.com/vim-airline/vim-airline/wiki/Screenshots
[[plugins]]
hook_add = """
let g:airline_theme='angr'
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#formatter='unique_tail'
let g:airline#extensions#tabline#buffer_idx_mode=1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#buffer_idx_format = {
    \ '0': '0 ',
    \ '1': '1 ',
    \ '2': '2 ',
    \ '3': '3 ',
    \ '4': '4 ',
    \ '5': '5 ',
    \ '6': '6 ',
    \ '7': '7 ',
    \ '8': '8 ',
    \ '9': '9 '
    \}
let g:airline#extensions#branch#enabled=1
let g:airline#extensions#hunks#enabled=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#wordcount#enabled=1
let g:airline#extensions#branch#vcs_checks = []
let g:airline#extensions#default#layout=[['a', 'b', 'c'], ['wordcount', 'error', 'warning', 'x', 'y', 'z']]
let g:airline_section_c = '%t'
"""
repo = 'vim-airline/vim-airline'

[[plugins]]
hook_add = """
let g:indent_guides_enable_on_vim_startup=1 "デフォルトでインデント出す
let g:indent_guides_start_level=2 "ガイドをスタートするインデント
let g:indent_guides_guide_size=2 " ガイドの幅
let g:indent_guides_auto_colors = 2
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=NONE "奇数インデントのカラー
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=NONE "偶数インデントのカラー
"""
repo = 'nathanaelkane/vim-indent-guides'


## shortuts
[[plugins]]
hook_add = """
    nnoremap <C-/> <Plug>RepeatTComment<CR>
"""
repo = 'tomtom/tcomment_vim' # comment out

[[plugins]]
repo = 'easymotion/vim-easymotion' # make it easy to move few words

[[plugins]]
repo = 'windwp/nvim-ts-autotag'


## lsp
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
hook_add = '''
if executable('typescript-language-server')
au User lsp_setup call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'package.json'))},
"       \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
        \ 'whitelist': ['typescript', 'typescript.tsx', 'javascript', 'javascript.jsx'],
        \ })
endif
'''
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'shun/ddc-vim-lsp'
[[plugins]]
repo = 'Shougo/ddc-ui-native'
#Install Your Sources
[[plugins]]
repo = 'Shougo/ddc-source-around'
# Install your filters
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'matsui54/ddc-buffer'
# [[plugins]]
# reop = 'shun/ddc-source-vim-lsp'
[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/vim-vsnip'

### laravel
## これらはphp / composerをmacに入れておく必要があるのでやめた
# [[plugins]]
# hook_post_update = '''
#   if has('win32')
#     let cmd = 'tools\\update-dll-mingw'
#   elseif has('win32unix') " for Cygwin
#     let cmd = 'make -f make_cygwin.mak'
#   elseif executable('gmake')
#     let cmd = 'gmake'
#   else
#     let cmd = 'make'
#   endif
#   let g:dein#plugin.build = cmd
# '''
# [[plugins]]
# repo = 'Shougo/unite.vim'
# [[plugins]]
# depends = 'Vimproc'
# repo = 'm2mdas/phpcomplete-extended'
# [[plugins]] repo = 'm2mdas/phpcomplete-extended-laravel'

### js
[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
hook_add = '''
    source ~/.config/nvim/plugins/vim-vue.rc.vim
'''
repo = 'posva/vim-vue'


[[plugins]]
on_ft = ['pug', 'vue']
repo = 'digitaltoad/vim-pug'

[[plugins]]
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
repo = 'prettier/vim-prettier'


[[plugins]]
repo = 'alvan/vim-closetag'

## copilot
[[plugins]]
repo = 'github/copilot.vim'
